site_name: Reserva Alberdi 

# Copyright
copyright: 'Copyright &copy; 2024 - 2025 Noeli Baeza'

theme:
  name: material
  logo: imagenes/logosinfondo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - header.autohide
    - navigation.footer
  font:
   text: Google Sans
   code: Regular
  favicon: imagenes/favicon.ico
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: light green
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: light green
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/pex.reservaesc.alberdi?igsh=MWd3dTFhdG84N2pndw==
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/PEX.ReservaNaturalEscuelaAlberdi 

extra_css:
  - stylesheets/extra.css


nav:
  - Inicio: index.md
  - Actividades: actividades.md
  - Proyectos: presentaciones.md
  - Galeria: galeria.md
  - Contacto: contacto.md
  - Recorridos: recorridos.md
